name: Générer le PDF hebdomadaire

on:
  schedule:
    - cron: '0 9 * * 1'  # Tous les lundis à 9h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install pandas feedparser feedgen fpdf

      - name: Générer le flux RSS combiné
        run: |
          python generate_script.py

      - name: Générer le PDF à partir du XML
        run: |
          python generate_pdf_from_xml.py
