name: Weekly Press Review

on:
  schedule:
    - cron: '0 9 * * 1'  # Tous les lundis à 9h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate combined RSS feed
      run: python combine_rss_feeds.py

    - name: Generate PDF from RSS
      run: python generate_pdf_from_rss.py

    - name: Send PDF by email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Weekly Press Review
        to: natanael@example.com
        from: GitHub Actions <natanael.farret@hertz.com>
        body: |
          Bonjour Natanael,

          Veuillez trouver en pièce jointe la revue de presse hebdomadaire.

          Bien cordialement,
          GitHub Actions
        attachments: weekly_press_review.pdf
