name: Weekly Press Review

on:
  schedule:
    - cron: '0 9 * * 1'  # Tous les lundis à 9h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate combined RSS feed
      run: python combine_rss_feeds.py

    - name: Generate PDF from RSS
      run: python generate_pdf_from_rss.py

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: weekly-press-review
        path: weekly_press_review.pdf
